openapi: '3.0.3'
info:
  title: "Category RESTful API"
  description: "API Spec for Category RESTful API"
  version: '1.0'
servers:
  - url: "http://localhost:3020/api"
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
